config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'notebook/my_notes'
  resources :notes
  resources :users
  get 'session/login'
  post 'session/create'
  get 'session/logout'

  root to: 'notebook#my_notes'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
# frozen_string_literal: true

class Note < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  has_many :notes
  validates :username, uniqueness: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include SessionHelper
  before_action :require_login
  around_action :switch_locale

  private

  def require_login
    redirect_to :session_login unless signed_in?
  end

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end
end

app/controllers/notebook_controller.rb
# frozen_string_literal: true

class NotebookController < ApplicationController
  skip_before_action :require_login, only: %i[main_page cook_page]
  def my_notes
    @notes = Note.where(user_id: current_user.id).all.map do |n|
      { id: n.id, header: n.header, content: n.content, user_id: n.user_id }
    end
  end
end

app/controllers/notes_controller.rb
# frozen_string_literal: true

class NotesController < ApplicationController
  before_action :set_note, only: %i[show edit update destroy]
  skip_before_action :require_login, only: %i[show]

  # GET /notes or /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1 or /notes/1.json
  def show; end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit; end

  # POST /notes or /notes.json
  def create
    @note = Note.new(**note_params, user_id: current_user.id)

    respond_to do |format|
      if @note.save
        format.html { redirect_to note_url(@note), notice: t('info.note_was_created') }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to note_url(@note), notice: t('info.note_was_updated') }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: t('info.note_was_destroyed') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_note
    @note = Note.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def note_params
    params.require(:note).permit(:header, :content)
  end
end

app/controllers/session_controller.rb
# frozen_string_literal: true

class SessionController < ApplicationController
  skip_before_action :require_login

  def login; end

  def create
    user = User.find_by(username: params[:username])

    if user&.authenticate(params[:password])
      sign_in user
      redirect_to root_path
    else
      redirect_to session_login_path
    end
  end

  def logout
    sign_out
    redirect_to session_login_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  skip_before_action :require_login

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        sign_in(@user)
        format.html { redirect_to root_path, notice: t('info.user_was_created') }
        format.json { render root_path, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: t('info.user_was_updated') }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to root_url, notice: t('info.user_was_destroyed') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/notebook_helper.rb
# frozen_string_literal: true

module NotebookHelper
end

app/helpers/notes_helper.rb
# frozen_string_literal: true

module NotesHelper
end

app/helpers/session_helper.rb
# frozen_string_literal: true

module SessionHelper
  def sign_in(user)
    cookies.signed[:user_id] = { value: user.id, expires: 1.hour }
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.signed[:user_id] = nil
    self.current_user = nil
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by(id: cookies.signed[:user_id])
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NoteBook</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<% if !current_page?(session_login_path) && !current_page?(new_user_path) %>
  <header class="d-flex justify-content-end" style="margin-bottom: 50px">
    <ul class="nav nav-pills">
      <li class="nav-item"><a href=<%= root_path %> class="nav-link" aria-current="page"><%= t('page.my_notes') %></a></li>
      <li class="nav-item"><a href="/users/<%= current_user.id %>" class="nav-link"><%= t('page.account') %></a></li>
      <li class="nav-item"><a class="nav-link" href=<%= session_logout_path %><%= t('logout') %>></a></li>
    </ul>
  </header>
<% end %>

<%= yield %>

<div class="footer mt-auto footer-expand-md fixed-bottom d-flex flex-wrap justify-content-between align-items-center py-3 border-top" style="background-color: #cddfff; margin-top: 30px">
  <div class="col-md-4 d-flex align-items-center">
    <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
      <svg class="bi" width="30" height="24">
        <use xlink:href="#bootstrap"></use>
      </svg>
    </a>
    <span class="text-muted">© Alexey Zamarin, IS6-35B</span>
  </div>
</div>

</body>
</html>

app/views/notebook/my_notes.html.erb
<div class="container-md">
  <div class="row">
    <div class="col-8">
      <h4 style="margin: 20px"><%= t('page.my_notes') %></h4>
    </div>
    <div class="col-4 d-flex justify-content-center" style="align-self: center">
      <%= button_to(t('page.add_note'), new_note_path, method: :get, class: "btn btn-outline-primary") %>
    </div>
  </div>
  <div class="row">
    <% if @notes.empty? %>
      <div> <%= t('page.my_notes') %></div>
    <% else %>
      <% @notes.each do |note| %>
        <div class="card">
          <div class="card-header"><h5><%= note[:header] %></h5></div>
          <div class="card-body">
            <a href="/notes/<%= note[:id] %>" class="btn btn-outline-primary"> <%= t('page.details') %></a>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/notes/edit.html.erb
<div class="form-note">
  <% if @note.errors.any? %>
    <div class="alert alert-danger" role="alert"><%= t('error.empty_gaps') %></div>
  <% end %>
  <%= form_with(model: @note, local: true, class: "row g-3") do |form| %>
    <h1 class="h3 mb-3 fw-normal" style="margin-top: 50px"></h1>
    <div class="row g-2">
      <div class="form-floating">
        <%= form.text_field :header, required: true, class: "form-control", :placeholder => t('note.header') %>
        <label for="floatingInput" style="margin-left: 10px"><%= t('note.header') %></label>
      </div>
    </div>
    <div class="row g-2">
      <div class="form-floating">
        <%= form.text_area :content, required: true, class: "form-control", :placeholder => t('note.content') %>
        <label for="floatingInput" style="margin-left: 10px"><%= t('note.content') %></label>
      </div>
    </div>
    <div class="col-1"></div>
    <div class="col-10">
      <%= form.submit value: t('save'), class: "w-100 btn btn-primary" %>
    </div>
  <% end %>

</div>

app/views/notes/new.html.erb
<div class="form-note">

  <% if @note.errors.any? %>
    <div class="alert alert-danger" role="alert">t('error.empty_gaps')</div>
  <% end %>
  <%= form_with(model: @note, local: true, class: "row g-3") do |form| %>

    <h1 class="h3 mb-3 fw-normal" style="margin-top: 50px"><%= t('page.add_note') %></h1>

    <div class="row g-2">
      <div class="form-floating">
        <%= form.text_field :header, required: true, class: "form-control", :placeholder => t('note.header') %>
        <label for="floatingInput" style="margin-left: 10px"><%= t('note.header') %></label>
      </div>
    </div>
    <div class="row g-2">
      <div class="form-floating">
        <%= form.text_area :content, required: true, class: "form-control", :placeholder => t('note.content') %>
        <label for="floatingInput" style="margin-left: 10px"><%= t('note.content') %></label>
      </div>
    </div>
    <div class="row g-2" style="justify-content: center">
      <div class="col-6" style="margin-bottom: 40px; margin-top: 20px">
        <%= form.submit value: t('page.add_note'), class: "w-100 btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/notes/show.html.erb
<div class="container">
  <div class="row" style="margin-bottom: 40px; margin-top: 40px">
    <div class="col-8"><h2><%= @note.header %></h2></div>
    <div class="col-2" style="align-content: center">
      <div class="btn-group" role="group" aria-label="Basic outlined example">
        <%= button_to(t('change'), edit_note_path(@note), method: :get, class: "btn btn-outline-primary") %>
        <%= button_to(t('delete'), @note, :method => "delete", data: true, class: "btn btn-outline-primary", style: "margin-left: 15px") %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-6"><%= @note.content %></div>
  </div>

</div>

app/views/session/login.html.erb
<div class="container form-sign-in align-content-center justify-content-center">
  <h1 class="h3 fw-normal" style="margin-top: 70px; margin-bottom: 50px">Вход</h1>
  <%= form_with url: session_create_url, method: :post, local: true,class:'row g-3 justify-content-center' do |f| %>
    <div class="form-floating">
      <%= f.text_field :username, required: true, class: 'form-control',placeholder:t('user.username')%>
      <%= f.label :username,t('user.username'),style:"margin-left: 10px"%>
    </div>
    <div class="form-floating">
      <%= f.password_field :password, required: true, class: 'form-control',placeholder:t('user.password')%>
      <%= f.label :password,t('user.password'),style:"margin-left: 10px"%>
    </div>
    <%= f.submit 'Войти', class:'col-4 btn btn-lg btn-primary'%>
  <% end %>
  <%= link_to t('register'), new_user_path %>
</div>

app/views/users/edit.html.erb
<div class="form-sign-in">
  <% if @user.errors.any? %>
    <div class="alert alert-danger" role="alert"><%= t('error.empty_gaps') %></div>
  <% end %>
  <%= form_with(model: @user, local: true, class: "row g-3") do |form| %>
    <h1 class="h3 mb-3 fw-normal" style="margin-top: 50px"><%= t('page.user_data_edition') %></h1>

    <div class="row g-2">
      <div class="form-floating">
        <%= form.text_field :name, required: true, class: "form-control", :placeholder => t('user.name') %>
        <label for="floatingInput" style="margin-left: 10px"><%= t('user.name') %></label>
      </div>
    </div>

    <div class="row g-2">
      <div class="form-floating">
        <%= form.text_field :username, required: true, class: "form-control", :placeholder => t('user.username') %>
        <label for="floatingInput" style="margin-left: 10px"><%= t('user.username') %></label>
      </div>
    </div>

    <div class="row g-2">
      <div class="form-floating">
        <%= form.email_field :email, required: true, class: "form-control", :placeholder => t('user.email') %>
        <label for="floatingInput" style="margin-left: 10px"><%= t('user.email') %></label>
      </div>
    </div>

    <div class="row g-2">
      <div class="col">
        <div class="form-floating">
          <%= form.password_field :password, required: true, class: "form-control", :placeholder => t('user.password') %>
          <label for="floatingInput" style="margin-left: 10px"><%= t('user.password') %></label>
        </div>
      </div>
      <div class="col">
        <div class="form-floating">
          <%= form.password_field :password_confirmation, required: true, class: "form-control", :placeholder => t('user.conf_password') %>
          <label for="floatingInput" style="margin-left: 10px"><%= t('user.conf_password') %></label>
        </div>
      </div>
    </div>
    <div class="row g-2 justify-content-center">
      <div class="btn-lg col-6">
        <%= form.submit value: t('save'), required: true, class: "w-100 btn btn-primary" %>
      </div>
    </div>

  <% end %>
  </form>
</div>

app/views/users/new.html.erb
<div class="form-sign-in">

  <%= form_with(model: @user, local: true, class: "row g-3") do |form| %>
    <h1 class="h3 mb-3 fw-normal" style="margin-top: 50px"><%= t('login') %></h1>

    <div class="row g-2">
      <div class="form-floating">
        <%= form.text_field :name, required: true, class: "form-control", :placeholder => t('user.name') %>
        <label for="floatingInput" style="margin-left: 10px"><%= t('user.name') %></label>
      </div>
    </div>
    <div class="row g-2">
      <div class="form-floating">
        <%= form.text_field :username, required: true, class: "form-control", :placeholder => t('user.username') %>
        <label for="floatingInput" style="margin-left: 10px"><%= t('user.username') %></label>
      </div>
    </div>
    <div class="row g-2">
      <div class="form-floating">
        <%= form.email_field :email, required: true, class: "form-control", :placeholder => t('user.email') %>
        <label for="floatingInput" style="margin-left: 10px"><%= t('user.email') %></label>
      </div>
    </div>
    <div class="row g-2">
      <div class="col">
        <div class="form-floating">
          <%= form.password_field :password, required: true, class: "form-control", :placeholder => t('user.password') %>
          <label for="floatingInput" style="margin-left: 10px"><%= t('user.password') %></label>
        </div>
      </div>
      <div class="col">
        <div class="form-floating">
          <%= form.password_field :password_confirmation, required: true, class: "form-control", :placeholder => t('user.conf_password') %>
          <label for="floatingInput" style="margin-left: 10px"><%= t('user.conf_password') %></label>
        </div>
      </div>
    </div>

    <div class="col-1"></div>
    <div class="col-10"><%= form.submit value: t('save'), class: "w-100 btn btn-primary" %></div>
    <div class="col-1"></div>

  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">

  <div class="row" style="margin-bottom: 10px">
    <div class="col-2"></div>
    <div class="col-4">
      <h3><%= t('page.account') %></h3>
    </div>
    <div class="col-4 d-flex justify-content-end">
      <%= button_to(t('change'), edit_user_path(@user), method: :get, class: "btn btn-outline-primary") %>
    </div>
    <div class="col-2"></div>
  </div>

  <div class="row">
    <div class="col-2"></div>
    <div class="col-8">
    <ul class="list-group">
      <li class="list-group-item"><label style="margin-right: 5px"><%= t('user.name') %>: </label><span><%= @user.name %></span></li>
      <li class="list-group-item"><label style="margin-right: 5px"><%= t('user.username') %>: </label><span><%= @user.username %></span></li>
      <li class="list-group-item"><label style="margin-right: 5px"><%= t('user.email') %>: </label><span><%= @user.email %></span></li>
    </ul>
    </div>
    <div class="col-2"></div>
  </div>

</div>